# Site settings
title: Hushmail Blog
email: anabeli@hush.com
description: "Security and privacy"
baseurl: "blog"
url: "https://www.hushmail.com"
twitter_username: hushmail

# Build settings
markdown: kramdown
permalink: pretty
